=== kokolorix/wEBcMD/wEBcMD/tools/types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com) by devil (hell-soft) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Types">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="ObjectType" type="ObjT"/>
				<xs:element name="ObjectWrapper" type="ObjWrapT"/>
				<xs:element name="CommandWrapper" type="CmdWrapT"/>
			</xs:choice>
			<!-- <xs:sequence maxOccurs="unbounded"> -->
			<!-- </xs:sequence> -->
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ValT">
		<xs:restriction base="xs:string">
			<xs:pattern value="Void"/>
			<xs:pattern value="Boolean(\s*\[\s*\])?"/>
			<xs:pattern value="Int32(\s*\[\s*\])?"/>
			<xs:pattern value="UInt32(\s*\[\s*\])?"/>
			<xs:pattern value="Int64(\s*\[\s*\])?"/>
			<xs:pattern value="UInt64(\s*\[\s*\])?"/>
			<xs:pattern value="Double(\s*\[\s*\])?"/>
			<xs:pattern value="String(\s*\[\s*\])?"/>
			<xs:pattern value="UuId(\s*\[\s*\])?"/>
			<xs:pattern value="PropertyDTO(\s*\[\s*\])?"/>
			<xs:pattern value="PropertyTypeDTO(\s*\[\s*\])?"/>
			<xs:pattern value="AdressDTO(\s*\[\s*\])?"/>
			<xs:pattern value=""/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UseT">
		<xs:restriction base="xs:string">
			<xs:enumeration value="requred"/>
			<xs:enumeration value="optional"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UuIdT">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="BaseT">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="category" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ObjT">
		<xs:complexContent>
			<xs:extension base="BaseT">
				<xs:sequence>
					<xs:sequence minOccurs="0">
						<xs:element name="Summary"/>
					</xs:sequence>
					<xs:element name="Base" type="BaseT"/>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="PropertyType" type="PropT"/>
					</xs:sequence>
				</xs:sequence>
				<xs:attribute name="id" type="UuIdT" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PropT">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Summary"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="ValT" use="required"/>
		<xs:attribute name="use" type="UseT" use="optional"/>
		<xs:attribute name="default" type="xs:string" use="optional"/>
		<xs:attribute name="summary" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ObjWrapT">
		<xs:complexContent>
			<xs:extension base="ObjT">
				<xs:sequence>
					<xs:element name="DTO" type="BaseT"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CmdT">
		<xs:complexContent>
			<xs:extension base="BaseT">
				<xs:sequence>
					<xs:sequence minOccurs="0">
						<xs:element name="Summary"/>
					</xs:sequence>
					<xs:element name="Base" type="BaseT"/>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="ParameterType" type="ParamT"/>
					</xs:sequence>
				</xs:sequence>
				<xs:attribute name="id" type="UuIdT" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ParamT">
		<xs:complexContent>
			<xs:extension base="PropT">
				<xs:attribute name="modifier" use="optional" default="inout">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="in"/>
							<xs:enumeration value="out"/>
							<xs:enumeration value="inout"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CmdWrapT">
		<xs:complexContent>
			<xs:extension base="CmdT">
				<xs:sequence>
					<xs:element name="DTO" type="BaseT"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== kokolorix/wEBcMD/Types/AdressTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
	<ObjectType name="AdressDTO" category="Adresses" id="71959238-5bfd-459b-8fba-e48657d8ff2b">
		<Summary/>
		<Base name="BaseDTO" category="Base"/>
		<PropertyType name="Name1" type="String" summary=""/>
		<PropertyType name="Name2" type="String" summary=""/>
		<PropertyType name="Adress1" type="String" summary=""/>
		<PropertyType name="Adress2" type="String" summary=""/>
		<PropertyType name="Housenumber" type="String" summary=""/>
		<PropertyType name="City" type="String" summary=""/>
		<PropertyType name="Postcode" type="String" summary=""/>
	</ObjectType>
	<CommandWrapper name="FindAdresses" category="Adresses" id="13b2f4da-711a-451e-b435-2c2dc1fbbe4e">
		<Summary/>
		<Base name="CommandWrapper"/>
		<ParameterType name="SearchText" type="String">
		</ParameterType>
		<ParameterType name="SearchResult" type="AdressDTO[]" summary=""/>
		<DTO name="CommandDTO"/>
	</CommandWrapper>
</Types>

=== kokolorix/wEBcMD/wEBcMD/Types/BaseTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
	<ObjectType name="BaseDTO" category="Base" id="1a81bc99-28c2-4c03-ac5c-a1de4967cc36">
		<Base name="" category=""/>
		<PropertyType name="Id" type="UuId"/>
		<PropertyType name="Type" type="UuId"/>
	</ObjectType>
	<ObjectType name="PropertyDTO" category="Base" id="24ef4fd2-e337-4baa-89dd-404a72200871">
		<Base name="" category=""/>
		<PropertyType name="Name" type="String"/>
		<PropertyType name="Value" type="String"/>
	</ObjectType>
	<ObjectType name="ObjectDTO" category="Base" id="1a81bc99-28c2-4c03-ac5c-a1de4967cc36">
		<Base name="BaseDTO" category="Base"/>
		<PropertyType name="Properties" type="PropertyDTO[]"/>
	</ObjectType>
	<ObjectType name="TypeDTO" category="Base" id="2c8c1feb-0d04-45d2-bbe7-fe137450412e">
		<Base name="BaseDTO" category="Base"/>
		<PropertyType name="Name" type="String"/>
	</ObjectType>
	<!-- <ObjectType name="DatatypeDTO" id="91d670c8-dedd-41c9-8407-7532b1fad45a">
		<Base name="" />
		<PropertyType name="Type" type="Enum=String,Boolean,Double,Int32,*DTO"/>
	</ObjectType> -->
</Types>

=== kokolorix/wEBcMD/wEBcMD/Types/AdressTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
   <Summary>
      Types and Commands around Adresses.
   </Summary>
	<ObjectType name="AdressDTO" category="Adresses" id="71959238-5bfd-459b-8fba-e48657d8ff2b">
		<Summary/>
		<Base name="BaseDTO" category="Base"/>
		<PropertyType name="Name1" type="String" summary="First name of the person or name of the company"/>
		<PropertyType name="Name2" type="String" summary="Surname of the person or additional name of the company"/>
		<PropertyType name="Adress1" type="String" summary="Street name"/>
		<PropertyType name="Adress2" type="String" summary="Address supplement"/>
		<PropertyType name="Housenumber" type="String" summary="House no."/>
		<PropertyType name="City" type="String" summary="Village"/>
		<PropertyType name="Postcode" type="String" summary="Postal code"/>
	</ObjectType>
	<CommandWrapper name="FindAdresses" http="get" category="Adresses" id="13b2f4da-711a-451e-b435-2c2dc1fbbe4e">
		<Summary>Addresses search, with multiple tokens</Summary>
		<Base name="CommandWrapper"/>
		<ParameterType name="SearchText" type="String" modifier="in" summary="Search text, can contain several words separated by spaces"/>
		<Result type="AdressDTO[]" summary="The result of the search is a list of AddressDTO objects"/>
		<DTO name="CommandDTO"/>
	</CommandWrapper>
	<CommandWrapper name="GetAdress" http="get" category="Adresses" id="c6771f60-a64b-4775-a006-a2bce00b23a4">
		<Summary/>
		<Base name="CommandWrapper"/>
		<ParameterType name="Id" type="UuId" modifier="in"/>
		<Result type="AdressDTO" summary="The address found or null if it does not exist" />
		<DTO name="CommandDTO"/>
	</CommandWrapper>
	<CommandWrapper name="SetAdress" http="post" category="Adresses" id="c84bb99b-2d11-4426-87fa-119dc892f4ec">
		<Summary>Updates an existing address if Id is specified,
or creates a new one if Id is null.
The updated or newly created address is returned in Result.</Summary>
		<Base name="CommandWrapper"/>
		<ParameterType name="Id" type="UuId" modifier="in"/>
		<ParameterType name="Adress" type="AdressDTO" summary="The address which should be saved, or null if it should be deleted." modifier="in"/>
		<Result type="AdressDTO" summary="The address stored"/>
		<DTO name="CommandDTO"/>
	</CommandWrapper>
   <CommandWrapper name="DeleteAdress" http="delete" id="c60a9e66-b60a-4228-a7e5-ca61285ce5de">
      <Summary>Delete the Adress with the given id.
         Returns the Adress which was deleted.</Summary>
      <Base name="CommandWrapper"/>
		<ParameterType name="Id" type="UuId" modifier="in"/>
		<Result type="AdressDTO" summary="The deleted address"/>
		<DTO name="CommandDTO"/>
   </CommandWrapper>
</Types>

=== kokolorix/wEBcMD/wEBcMD/Types/CommandTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Types
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
	<ObjectType name="CommandDTO" category="Types" id="c1eda1fc-cc45-4658-889f-ccd989c2848a">
		<Summary>         Base command object. Has all arguments in generig list,          can be wrapped by concrete command wrappers         </Summary>
		<Base name="BaseDTO" category="Base"/>
		<PropertyType name="Response" type="Boolean" default="false" summary="Indicates if this is the answer"/>
		<PropertyType name="Arguments" type="PropertyDTO[]" default="[]" summary="Arguments of the command"/>
		<!-- <PropertyType name="Default" type="PropertyDTO" summary="Default Argument of the command"/> -->
	</ObjectType>
	<ObjectType name="ParamDTO" id="95f50f9b-9e6c-4f72-8bfe-486adffda5a9">
		<Base name="" />
		<PropertyType name="Name" type="String"/>
		<PropertyType name="Type" type="String"/>
	</ObjectType>
	<ObjectType name="CommandTypeDTO" id="7e4e81c9-9170-4f9e-bfe0-b9acd359958b">
		<Base name="TypeDTO" />
		<PropertyType name="Result" type="String"/>
		<PropertyType name="Parameters" type="ParamDTO[]"/>
	</ObjectType>
	<CommandWrapper name="GetCommandTypes" http="get" category="Command" id="6dab2a85-0256-421c-8a7a-2337453a3e48">
		<Summary>Get a list of all Command-Types</Summary>
		<Base name="CommandWrapper"/>
		<!-- <ParameterType name="SearchText" type="String" modifier="in" summary="Search text, can contain several words separated by spaces"/> -->
		<Result type="CommandTypeDTO[]" summary="The command type object"/>
		<DTO name="CommandDTO"/>
	</CommandWrapper>
	<CommandWrapper name="SampleCommand" http="post" category="Samples" id="e3e185bd-5237-4574-977f-a040bbe12d35">
		<Summary>
This is the sample command. He has two Parameters
and a multiline summary.
``` typescript
CommandDTO cmd;
if(SampleCommand.IsForMe(dto)){   let sample = new SampleCommand(cmd);   console.log(sample.FirstOne);
}
```
		</Summary>
		<Base name="CommandWrapper"/>
		<ParameterType name="FirstOne" type="String">
			<Summary>
The FirstOne is a string parameter
and has a multiline comment         </Summary>
		</ParameterType>
		<ParameterType name="SecondOne" type="Boolean" summary="The SecondOne is a boolean parameter"/>
		<DTO name="CommandDTO"/>
	</CommandWrapper>
</Types>

=== kokolorix/wEBcMD/wEBcMD/Types/ObjectTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Types
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
	<Summary></Summary>
	<ObjectType name="ObjectTypeDTO" category="Object" id="9b286c28-4baf-44dd-9328-9729854f4882">
		<Summary></Summary>
		<Base name="TypeDTO" category="Base"/>
	</ObjectType>
	<CommandWrapper name="GetObjectTypes" http="get" category="Object" id="058aa634-956c-4167-b5e0-2c2171ae55c0">
		<Summary></Summary>
		<Base name="CommandWrapper" category="Base"/>
		<Result type="ObjectTypeDTO[]" summary="" />
		<DTO name="CommandDTO"/>
	</CommandWrapper>
</Types>

=== kokolorix/wEBcMD/Types/BaseTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com)-->
<Types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
	<ObjectType name="PropertyDTO" category="Base" id="24ef4fd2-e337-4baa-89dd-404a72200871">
		<PropertyType name="Name" type="String"/>
		<PropertyType name="Type" type="String"/>
		<PropertyType name="Value" type="String"/>
	</ObjectType>
	<ObjectType name="BaseDTO" category="Base" id="1a81bc99-28c2-4c03-ac5c-a1de4967cc36">
		<Base name="" category=""/>
		<PropertyType name="Id" type="UuId"/>
		<PropertyType name="Type" type="UuId"/>
		<PropertyType name="Properties" type="PropertyDTO[]"/>
	</ObjectType>
	<ObjectType name="TypeDTO" category="Base" id="2c8c1feb-0d04-45d2-bbe7-fe137450412e">
		<Base name="BaseDTO" category="Base"/>
	</ObjectType>
	<ObjectType name="TextDTO" category="Types" id="69082378-4fae-4bf5-adfc-ddecfbdf4bb5">
		<Base name="TypeDTO" category="Base"/>
		<PropertyType name="Encoding" type="String"/>
		<PropertyType name="MaxLength" type="UInt64"/>
	</ObjectType>
</Types>

=== kokolorix/wEBcMD/wEBcMD/Types/ExampleTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Types
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
	<Summary>		Detailed Description of the Command-Module.		Meaning and purpose, intentions and limitations.	</Summary>
	<ObjectType name="ExampleDTO" category="Samples" id="5c7fc88a-b15a-4a4b-b687-e320c44743de">
		<Summary>Description of the Data-Strucure.</Summary>
		<Base name="BaseDTO" category="Base"/>
		<PropertyType name="One" type="String" summary="First property, a string" />
		<PropertyType name="Two" type="Boolean" summary="Second one, a boolean"/>
	</ObjectType>
	<CommandWrapper name="Example" http="get" category="Samples" id="a84ca129-1d08-4864-a97d-50639b8055d5">
		<Summary>The very first command we designed</Summary>
		<Base name="CommandWrapper" category="Base"/>
		<ParameterType name="Id" type="UuId" modifier="in" summary="The Id of the Data-Object"/>
		<Result type="ExampleDTO" summary="The Data-Object" />
		<DTO name="CommandDTO"/>
	</CommandWrapper>
	<CommandWrapper name="EchoValue" http="post" category="Samples" id="69c8864e-dc43-48ac-9865-99cac19aa5c0">
		<Summary>A command, that returns the given value</Summary>
		<Base name="CommandWrapper" category="Base"/>
		<ParameterType name="value" type="ValueDTO" modifier="in" summary="The value to deserialize"/>
		<Result type="ValueDTO" summary="The serialized value" />
		<DTO name="CommandDTO"/>
	</CommandWrapper>
	<CommandWrapper name="EchoArguments" http="post" category="Samples" id="1de8430f-bd11-4747-8455-698952b8ce49">
		<Summary>A  command that returns the given arguments</Summary>
		<Base name="CommandWrapper" category="Base"/>
		<ParameterType name="arguments" type="ArgumentDTO[]" modifier="in" summary="The argument list to deserializ"/>
		<Result type="ArgumentDTO[]" summary="The serialized list of arguments" />
		<DTO name="CommandDTO"/>
	</CommandWrapper>
</Types>

=== kokolorix/wEBcMD/Types/CommandTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com)-->
<Types
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\tools\types.xsd">
	<ObjectType name="CommandDTO" category="Types" id="c1eda1fc-cc45-4658-889f-ccd989c2848a">
		<Summary>         Base command object. Has all arguments in generig list,          can be derived by concrete command types         </Summary>
		<Base name="BaseDTO" category="Base"/>
		<PropertyType name="Response" type="Boolean" default="false" summary="Indicates if this is the answer"/>
		<PropertyType name="Arguments" type="PropertyDTO[]" summary="Arguments of the command"/>
	</ObjectType>
	<ObjectType name="SampleCommandDTO" category="Samples" id="e3e185bd-5237-4574-977f-a040bbe12d35">
		<Base name="CommandDTO" category="Types" />
		<PropertyType name="FirstOne" type="String" fromList="Arguments"></PropertyType>
		<PropertyType name="SecondOne" type="Boolean" fromList="Arguments"></PropertyType>
	</ObjectType>
</Types>
